name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"



[env.production.vars]
GITHUB_ID = "Ov23liDPXuF5D2GLzC2p"
GITHUB_OWNER = "alexlin1688"
GITHUB_REPO = "Navi"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://navi.lqw1688.dpdns.org/api/auth"
NEXT_PUBLIC_API_URL="https://navi.lqw1688.dpdns.org"

