name = "NavSphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"



[env.production.vars]
GITHUB_ID = "Ov23liBaQWiR88oQ3bwV"
GITHUB_OWNER = "alexlin1688"
GITHUB_REPO = "navsphere"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://alexlin1688.top/api/auth"
NEXT_PUBLIC_API_URL="https://alexlin1688.top"
NEXT_PUBLIC_SITE_URL="https://alexlin1688.top"
